CC=gcc

all:
		$(CC) catchSignal.c -g -o catchSignal
		$(CC) sigCount.c -g -o sigCount
		$(CC) shm_server.c -g -o shm_server
		$(CC) shm_client.c -g -o shm_client
clean:
		rm catchSignal sigCount shm_server shm_client
