CC=gcc

all:
		$(CC) catchSignal.c -g -o catchSignal
		$(CC) sigCount.c -g -o sigCount
		$(CC) shm_server.c -g -o shm_server
		$(CC) shm_client.c -g -o shm_client
		$(CC) timer.c -g -o timer
		$(CC) game.c -g -o game
		$(CC) guess.c -g -o guess
clean:
		rm catchSignal sigCount shm_server shm_client timer game guess
